language: node_js
node_js:
  - "0.10"
before_install:
  - "curl -L https://raw2.github.com/solvers/solvers/master/configure.sh | /bin/sh"
services:
  - mongodb
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e51550d6f5099e684b50
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false